### ISSUE TITLE
Flask-Migrate seems to not create tables on in-memory sqlite databases

### ISSUE THREAD

**Issue by ColdHeat** [miguelgrinberg/Flask-Migrate#153] opened 2017-03-23 15:10 UTC
With `SQLALCHEMY_DATABASE_URI = 'sqlite://'`,  upgrade() doesn't appear to create tables. 

My tests fail with:
`OperationalError: (sqlite3.OperationalError) no such table`

**Comment by miguelgrinberg** [comment] 2017-03-23 15:56
And you understand that as soon as the process exits the tables go away, right? So basically, if you run `flask db upgrade` the tables will be created, and then the in-memory database will disappear as the process ends.

**Comment by ColdHeat** [comment] 2017-03-23 16:13
Yes of course. The point of using it in tests is that the database will no longer exist once the test finishes so each test runs independent of the other.

**Comment by miguelgrinberg** [comment] 2017-03-23 16:14
How do you run the update then?

**Comment by ColdHeat** [comment] 2017-03-23 16:15
From the application factory:
https://github.com/CTFd/CTFd/blob/hints/CTFd/__init__.py#L49

Tests have a wrapper around the application factory:
https://github.com/CTFd/CTFd/blob/hints/tests/helpers.py#L8

**Comment by miguelgrinberg** [comment] 2017-03-23 16:50
It's isn't very clear what you are doing. It seems you are running the migrate command, but then you are also using sqlachemy_utils to drop and recreate the database, and finally run a db.create_all.

Do you have the log output from the migrate command? That should indicate what actions Alembic took as part of the upgrade.

**Comment by ColdHeat** [comment] 2017-03-23 23:19
```
alembic.runtime.migration: INFO: Context impl SQLiteImpl.
alembic.runtime.migration: INFO: Will assume non-transactional DDL.
alembic.runtime.migration: INFO: Running upgrade  -> cb3cfcc47e2f, Base 1.0.0 CTFd database
alembic.runtime.migration: DEBUG: new branch insert cb3cfcc47e2f
alembic.runtime.migration: INFO: Running upgrade cb3cfcc47e2f -> 87733981ca0e, Adds challenge types and uses keys table
alembic.runtime.migration: DEBUG: update cb3cfcc47e2f to 87733981ca0e
alembic.runtime.migration: INFO: Running upgrade 87733981ca0e -> a4e30c94c360, Add data column to keys table
alembic.runtime.migration: DEBUG: update 87733981ca0e to a4e30c94c360
alembic.runtime.migration: INFO: Running upgrade a4e30c94c360 -> d6514ec92738, Adding max_attempts to Challenges
alembic.runtime.migration: DEBUG: update a4e30c94c360 to d6514ec92738
alembic.runtime.migration: INFO: Running upgrade d6514ec92738 -> c7225db614c1, Adding Hints and Unlocks tables
alembic.runtime.migration: DEBUG: update d6514ec92738 to c7225db614c1
```

Ultimately this ends with:

```
OperationalError: (sqlite3.OperationalError) no such table: config [SQL: u'SELECT config.id AS config_id, config."key" AS config_key, config.value AS config_value \nFROM config \nWHERE config."key" = ?\n LIMIT ? OFFSET ?'] [parameters: ('ctf_version', 1, 0)]
```
since the tables weren't created.

**Comment by miguelgrinberg** [comment] 2017-03-23 23:30
I suggest that for testing, you add some database operation right after the upgrade call, like maybe inserting an item in your `config` table. I think that will work fine, because as far as I can see Alembic is doing the upgrade. I think something must be happening between that and when the actual test executes that wipes out your in-memory db.

And you haven't commented on your use of sqlalchemy_utils to drop/recreate the database, right after the upgrade.

**Comment by ColdHeat** [comment] 2017-03-23 23:36
You mean the create_database call before migrate_upgrade()? Flask-Migrate doesn't create the database if it doesn't exist in the case of MySQL. 

I'll take a look around for something that causes the database to get wiped.

**Comment by miguelgrinberg** [comment] 2017-03-23 23:37
@ColdHeat No, see the link I included in my reply above. After you call `create_app`, which in turn calls `migrate`, you drop/recreate your database.

**Comment by ColdHeat** [comment] 2017-03-23 23:40
I don't remember exactly why I wrote that, I believe it was to wipe out the database if the configured database was MySQL.

**Comment by ColdHeat** [comment] 2017-03-23 23:40
I've uncommented it and it doesn't affect the result of the test. They still fail for some reason.

**Comment by mcouthon** [comment] 2017-04-24 08:24
This is my experience as well - when running with `sqlite:///:memory:` the tables are not created. If I change `:memory:` to `app.db` (or whatever) the tests run fine.

**Comment by miguelgrinberg** [comment] 2017-04-24 14:36
@mcouthon try using `sqlite://` as your URL. See the [documentation](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite).

**Comment by mcouthon** [comment] 2017-04-24 15:21
@miguelgrinberg Tried it, getting the same result

**Comment by miguelgrinberg** [comment] 2017-04-24 15:43
@mcouthon what's the error? Please include the stack trace.

**Comment by mcouthon** [comment] 2017-04-25 10:45
@miguelgrinberg Here is the traceback, that says the table doesn't exist. Again, changing the SQLA url from `sqlite://` to `sqlite://app.db` makes it work.

```
======================================================================
ERROR: test_get_empty (manager_rest.test.endpoints.test_blueprints.BlueprintsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pavel/dev/repos/cloudify-manager/rest-service/manager_rest/test/base_test.py", line 126, in setUp
    self._handle_flask_app_and_db(server_module)
  File "/Users/pavel/dev/repos/cloudify-manager/rest-service/manager_rest/test/base_test.py", line 179, in _handle_flask_app_and_db
    self._handle_default_db_config(server)
  File "/Users/pavel/dev/repos/cloudify-manager/rest-service/manager_rest/test/base_test.py", line 196, in _handle_default_db_config
    admin_password=admin_user['password'],
  File "/Users/pavel/dev/repos/cloudify-manager/rest-service/manager_rest/storage/storage_utils.py", line 45, in create_default_user_tenant_and_roles
    admin_role = _create_roles()
  File "/Users/pavel/dev/repos/cloudify-manager/rest-service/manager_rest/storage/storage_utils.py", line 62, in _create_roles
    return user_datastore.find_role(constants.ADMIN_ROLE)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/flask_security/datastore.py", line 206, in find_role
    return self.role_model.query.filter_by(name=role).first()
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2697, in first
    ret = list(self[0:1])
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2489, in __getitem__
    return list(res)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2796, in __iter__
    self.session._autoflush()
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1373, in _autoflush
    util.raise_from_cause(e)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1363, in _autoflush
    self.flush()
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/pavel/dev/venvs/cloudify/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) no such table: roles [SQL: u'INSERT INTO roles (name, description) VALUES (?, ?)'] [parameters: ('admin', None)]
```

**Comment by miguelgrinberg** [comment] 2017-04-25 14:41
My guess is that this access to the database precedes the place where the tables are created. Add a print statement in the `create_all()` call to verify that it happens before this error. In the case of a file, I think things work well because there is a previous database on disk.

**Comment by mcouthon** [comment] 2017-04-26 04:03
Sorry, I'm a bit confused - which `create_all()` call? I'm specifically running `upgrade()` _instead_ of `create_all()`.
And there isn't a previous DB on disk - this is a test suite and all the files we use in it are temporary and are deleted at the end of the test.
Also, thanks a lot for your help!

**Comment by miguelgrinberg** [comment] 2017-04-26 05:07
Do you create and delete your database file for every test? I still stand by my theory. The previous database file I mentioned does not need to be there before you run the tests. It can easily by a left over database from a previous test. Unfortunately I can't really help you much, this needs some debugging to figure out when the tables are created, when they are accessed and maybe when they are deleted. If the order is wrong, you'll end up with weird issues like these.

**Comment by jacol12345** [comment] 2017-07-12 13:08
Hi, I stumbled upon a similar issue with in-memory SQLite database. This is the fixture I am trying to get working:
```
@pytest.fixture()
def app():
    """An application for the tests."""
    _app = create_app(TestConfig)
    ctx = _app.test_request_context()
    ctx.push()

    yield _app

    ctx.pop()


@pytest.fixture
def db(request, app):
    _db.app = app
    with app.app_context():
        from flask_migrate import upgrade
        upgrade(directory=TestConfig.ALEMBIC_DIR)

    yield _db

    # Explicitly close DB connection
    _db.session.close()
    _db.drop_all()
```
I checked with pdb that alembic script is being executed but those changes are not reflected in tests. Using _db.create_all() works but I need to perform migrations in tests as they contain data upgrades. 
I'd prefer a cleaner solution than proposed here: https://gist.github.com/alexmic/7857543

**Comment by cryptomaniac512** [comment] 2018-01-01 12:36
I have the same issue when working with in-memory SQLite database.

**Comment by miguelgrinberg** [comment] 2018-01-02 06:45
@cryptomaniac512 do you have the code somewhere I can see it?

**Comment by cryptomaniac512** [comment] 2018-01-02 06:51
Fixture https://github.com/cryptomaniac512/try-flask-restful/blob/master/conftest.py#L9
Method used to init database https://github.com/cryptomaniac512/try-flask-restful/blob/master/try_flask/app.py#L18

I tried this with the following code and it does not work with in-memory sqlite
```python
    flask_app.config.update(
        SQLALCHEMY_DATABASE_URI='sqlite:///:memory:',
    )
    flask_app.init_db()
    upgrade(flask_app.migrate.directory)
```

**Comment by miguelgrinberg** [comment] 2018-01-02 07:06
The problem is that Alembic generates a separate connection to the database. So Alembic does its thing, then the connection is closed and that destroys the memory database. When your application starts using the database, it's a different one that also starts empty. Any reason you don't use `db.create_all()` for your tests? That is what I have always done, and never had a problem.

This is really between Alembic and SQLAlchemy, so you may want to see if Mike Bayer has an opinion on this issue.

**Comment by cryptomaniac512** [comment] 2018-01-02 07:09
I wanted to have the environment closest to production in the tests.
Now I use `create_all`, yes.

**Comment by miguelgrinberg** [comment] 2018-01-13 06:52
Closing, since this is not an issue with this project.

**Closed by miguelgrinberg** 2018-01-13 06:52 UTC
Labels: question
