### ISSUE TITLE
Flask db migrate/upgrade not responding

### ISSUE THREAD

**Issue by Victor7095** [miguelgrinberg/Flask-Migrate#384] opened 2021-02-08 00:26 UTC
Hi, I deleted the migrations folder, then ran `flask db init`, then `flask db migrate -m 'Test'`, but nothing happened, only got some messages:
```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```
The command `flask db upgrade` also shows the same message but nothing else.

**Comment by miguelgrinberg** [comment] 2021-02-08 10:54
Can you provide an example project that has this problem? I can't really tell you what's wrong, something is definitely missing but I don't know exactly what.

**Comment by qvik-olli** [comment] 2021-02-11 09:19
@miguelgrinberg, I can reproduce this issue with `flask-migrate==2.6.0`. This seems to happen when the database is in a revision that is not found in the migrations. With `flask-migrate==2.5.3` I get an error message "Can't locate revision identified by '...'", but `flask-migrate==2.6.0` doesn't display any error.

Steps to reproduce:
```sh
> pip install flask-migrate==2.6.0
> flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade xxx -> yyy
> rm migrations/yyy.py
> flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
# NO ERROR RETURNED HERE
> pip install flask-migrate==2.5.3
> flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [root] Error: Can't locate revision identified by 'yyy'

**Comment by miguelgrinberg** [comment] 2021-02-11 10:26
Why would you want to use an old release through? Old releases have to be installed from a requirements.txt file, because the dependencies might have changed since the release. In particular Alembic has been upgraded in a backwards incompatible way in this case.

**Comment by qvik-olli** [comment] 2021-02-11 10:45
I would not want to use an old release. I just noticed this after updating to `flask-migrate==2.6.0` (I'm using Alembic 1.5.4). Latest flask-migrate does not display an error message and fails silently when a revision can't be located. Previous version displays an error, so I thought it might be a regression in flask-migrate.

**Comment by miguelgrinberg** [comment] 2021-02-11 10:53
I think you have a misunderstanding related to how Alembic works. When you run `flask db migrate` Alembic compares the current state of the database with the current state of your models, and generates a migration script with the differences. 

So when you do this:

```
> pip install flask-migrate==2.6.0
> flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade xxx -> yyy
> rm migrations/yyy.py
> flask db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
# NO ERROR RETURNED HERE
```

The fact that you deleted a migration does not change anything. Your models and your database are still matching so there is nothing to do and for that reason Alembic just returns without doing anything. You will definitely have issues when you try to migrate the database again, because that migration script that you deleted introduced an inconsistency in your migration repository.

**Comment by qvik-olli** [comment] 2021-02-11 12:10
I'm definitely not expecting for the operation to be successful. I'm just expecting for an error message to be displayed. The cause of the issue seems to be this commit: https://github.com/miguelgrinberg/Flask-Migrate/commit/4887bd53bc08f10087fe27a4a7d9fe853031cdcf

flask-migrate doesn't use the root logger anymore, so `alembic.ini` needs to be updated to include configuration for `flask_migrate` logger.

**Comment by miguelgrinberg** [comment] 2021-02-12 10:38
Okay, you should have started by explaining the problem, I do understand now. This is now fixed in the master branch.

**Comment by josipbudzaki** [comment] 2021-02-12 13:10
Thanks for the update, that helped me to track down my problem as well!

**Comment by Victor7095** [comment] 2021-02-16 02:34
Sorry, I couldn't create an example code for testing. But I think the problem(not showing error message) is related to the `alembic_version` table. I just tried doind that again and didn't received an error message. Some steps I tried today.
- The `migrations/versions` folder had 5 registered migrations.
- I deleted the migrations folder but didn't deleted database and `alembic_version` table still had the last migration id.
- I ran `flask db init` and it created the migrations folder.
- Running `flask db migrate` doesn`t show any error message.
BUT, if I delete `alembic_version` table and run `flask db migrate` it shows: `No changes in schema detected`.
So, I guess I caused that just by messing with the migrations folder.

**Closed** 2021-02-16 10:33 UTC
Labels: question

**Comment by rmbkapil** [comment] 2022-11-15 09:37
It would be best if you imported your model's class in the __init__.py file. 
Then run the `flask db migrate` command and you are good to go

**Comment by Virendra1485** [comment] 2022-11-15 09:38
You just need to import models in the __init__.py file of package

**Comment by a3sha2** [comment] 2024-02-27 18:18
INFO [alembic.runtime.migration] Context impl SQLiteImpl.
